# Generated by Django 5.1.3 on 2024-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=False),
        ),
    ]
