# Generated by Django 5.0.6 on 2024-11-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nation", models.CharField(blank=True, max_length=50, null=True)),
                ("expiration", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "passport",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(max_length=60, unique=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("password", models.TextField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "passport_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="passport_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.passport",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
